# Generated by Django 3.1.4 on 2021-01-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('AT', 'статья'), ('NW', 'новость')], default='NW', max_length=2),
        ),
    ]
