# Generated by Django 3.1.4 on 2021-02-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210214_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='CategorySubscribers',
        ),
    ]
